version: 2.1
jobs:
  # Membuat workflow bernama build
  build:
    # Mendefinisikan image yang akan dipakai pada CI Pipeline
    docker:
      - image: cimg/go:1.15
    # Langkah-langkah dari CI Pipeline
    steps:
    # Checkout git branch
    - checkout
    # Step untuk menyiapkan environment docker
    - setup_remote_docker
    # Step bernama lint-dockerfile untuk lint Dockerfile
    - run:
        name: lint-dockerfile
        command: docker run --rm --interactive hadolint/hadolint < Dockerfile
    # Step bernama test-app untuk melakukan test pada code
    - run:
        name: test-app
        command: go test -v -short --count=1 $(go list ./...)
    # Step bernama build-app-karsajobs untuk build image dan push ke dockerhub dan github package
    - run:
        name: build-app-karsajobs
        command: |
          echo "Push image ke DockerHub..."
          docker build -t neithroid/karsajobs:latest .
          docker login -u neithroid -p ${PASSWORD_DOCKER_HUB}
          docker push neithroid/karsajobs:latest
          echo "Sukses push image ke repository Docker Hub"
          echo
          echo "Push image ke GitHub Container Registry..."
          docker tag neithroid/karsajobs:latest ghcr.io/dwikie/karsajobs:latest
          docker login ghcr.io -u dwikie -p ${PAT_GITHUB}
          docker push ghcr.io/dwikie/karsajobs:latest
          echo "Sukses push image ke repository GitHub"