name: publish
  on: [push]
  
jobs:
  publish-item-app-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Regsitry
        uses: actions/checkout@v3
      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build item-app image and push to ghcr
        run:
          docker run build --tag ghcr.io/dwikie/item-app:v1
          docker push ghcr.io/dwikie/item-app:v1